services:
  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
    ports:
      - "9870:9870"
    volumes:
      - hdfs-nn-data:/hadoop/dfs/name
    networks:
      - hadoopnet

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    depends_on:
      - hdfs-namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
      - HDFS_CONF_dfs_replication=1
    volumes:
      - hdfs-dn-data:/hadoop/dfs/data
    networks:
      - hadoopnet

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - hadoopnet

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    env_file:
      - .env
    depends_on:
      - spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    networks:
      - hadoopnet

  jupyter:
    image: quay.io/jupyter/pyspark-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - hadoopnet
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=""
      - JUPYTER_PASSWORD=""
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''



  airflow-db:
    image: postgres:15-alpine
    container_name: airflow-db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
    volumes:
      - airflow_db_data:/var/lib/postgresql/data 
    networks:
      - hadoopnet

  
  airflow-init:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-db
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
    networks:
      - hadoopnet
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
    ports:
      - "8082:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark-apps:/opt/spark-apps
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hadoopnet
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark-apps:/opt/spark-apps
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hadoopnet
    command: scheduler

  postgres:
    image: postgres:15
    container_name: cbn_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: cbn_analytics
    ports:
      - "5432:5432"
    volumes:
      - cbn_gold_data:/var/lib/postgresql/data
    networks:
      - hadoopnet         

volumes:
  hdfs-nn-data:
  hdfs-dn-data:
  airflow_db_data: 
  cbn_gold_data:   

networks:
  hadoopnet:
    driver: bridge